export const ProjectsArray = [
    {
        id: 1,
        title: "Lendsqr-Dashboard",
        name: "Lendsqr Dashboard",
        tagline: 'A Frontend Test Project for Lendsqr',
        discription: "The goal of this project is to build a portion of the Lendsqr dashboard where we can view the list of users and and check each user’s details.",
        status: 'Completed',
        tools: ['ReactJS', 'TypeScript', 'Sass'],
        githubLink: 'https://github.com/ImieboGodson/lendsqr-fe-test',
        liveLink: 'https://imiebo-godson-lendsqr-fe-test.vercel.app/',
    },
    {
        id: 2,
        title: "Zuri-Chat",
        name: "Zuri Chat",
        tagline: 'A Workspace Web App powered by React and Node Js.',
        discription: ``,
        status: 'Not Completed',
        tools: ['ReactJS', 'JavaScript', 'NodeJS', 'ExpressJS', 'CSS Modules'],
        githubLink: 'https://github.com/ImieboGodson/zc_main',
        liveLink: 'https://staging.zuri.chat/',
    },
    {
        id: 3,
        title: "Creer",
        name: "Creer",
        tagline: 'An Online Community for Local Developers.',
        discription: `This project is centered on enabling people within the tech ecosystem to share/get insights about issues encountered in the tech ecosystem. Many developers, as well as non-developers, have so many information ranging from project ideas to problems or solution to problems they have encountered that they wish to share in other to get solutions or feedback from peers in the ecosystem. This platform will serve as a "dumping ground" of information(problems/solutions/project ideas/insights) for the tech bros and sisters in the ecosystem.`,
        status: 'Not Completed',
        tools: ['ReactJS', 'JavaScript', 'Redux', 'Figma'],
        githubLink: 'https://github.com/ImieboGodson/creer-fe-pjt-105',
        liveLink: 'https://creer.vercel.app/',
    },
    {
        id: 4,
        title: "Color-Orgy",
        name: "Color Orgy",
        tagline: 'A curation of Nigerian music albums.',
        discription: `A curation of Nigerian music albums.`,
        status: 'Not Completed',
        tools: ['ReactJS', 'JavaScript', 'TailwindCSS', 'Vercel'],
        githubLink: 'https://github.com/tomiiide/color-orgy',
        liveLink: 'http://color-orgy.vercel.app/',
    },
]
